services:
   app:
      build: .
      container_name: reservoir_breathing_wave2
      volumes:
         - ../app/src:/root/app/src
         - ../app/data:/root/app/data
         - ../app/model:/root/app/model
         - ../app/lib:/root/app/lib
      stdin_open: true
      tty: true