services:
   app:
      build: .
      container_name: reservoir_breathing_wave2
      volumes:
         - ../app/src:/root/app/src
         - ../app/data:/root/app/data
         - ../app/model:/root/app/model
         - ../app/lib:/root/app/lib
         - ../app/.vscode:/root/app/.vscode
      #environment:
         # for Mac
         #- DISPLAY=host.docker.internal:0.0
      stdin_open: true
      tty: true
